runtime: nodejs16

handlers:
  - url: /dist
    static_dir: dist

  - url: /public
    static_dir: public

  - url: /.*
    script: auto

env_variables:
  ACCESS_TOKEN: pat-eu1-5fe19fee-9642-48fc-8494-0a9a9ca55d51
