runtime: nodejs16

handlers:
  - url: /src
    static_dir: src
    secure: always

  - url: /.*
    script: auto
    secure: always

env_variables:
  ACCESS_TOKEN: pat-eu1-5fe19fee-9642-48fc-8494-0a9a9ca55d51
